version: '3.9'

services:
  mysql_206:
    container_name: mysql_206
    hostname: mysql_206
    image: mysql:8.3
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: America/Sao_Paulo
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb_force_recovery=0
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_206:/var/lib/mysql
